;; This logfile was generated automatically by `xindy'
;; at 04.09.2018  20:32:10
;; Indexstyle: "/tmp/cxmDOvWXSQ", Rawindex: "/tmp/qUpFRemYq4", Output: "main.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "Ë_0" -> "R"
Letter-group: "_í—" -> "D"
Letter-group: "Úà»" -> "T"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "_í—" -> "D"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ë_0" -> "R"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Úà»" -> "T"